# Second Class Progress

### Numerical Operations on Numpy Arrays 

In [2]:
import numpy as np
lst = [2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
v = np.array(lst) 
v = v + 2
print(v)

[ 4.    5.    9.9   5.3   8.9   2.11 12.3  14.9 ]


### Arithmetic operations with two arrays

In [12]:
import numpy as np
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3), dtype = int)
print("Array created by ones: ")
print(B)
print("\n Adding to arrays: ")
print(A + B)
print("\n Multiplying two arrays: ")
print(A * B)

Array created by ones: 
[[1 1 1]
 [1 1 1]
 [1 1 1]]

 Adding to arrays: 
[[12 13 14]
 [22 23 24]
 [32 33 34]]

 Multiplying two arrays: 
[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Matrix Multiplication

For this purpose, we can use the dot product. Using the previous arrays, we can calculate the matrix
multiplication:
np.dot(A, B)

![title](dot.PNG)

In [16]:
print(np.dot(3, 9))
x = np.array([3])
y = np.array([7])
print(x.ndim)
print(np.dot(x, y))
x = np.array([8, -2])
y = np.array([-4, 1])
print(np.dot(x, y))

27
1
21
-34


Let's go to the two-dimensional use case:

In [17]:
A = np.array([ [1, 2, 3],[3, 2, 1] ])
B = np.array([ [2, 3, 4, -2], [1, -1, 2, 3], [1, 2, 3, 0] ])
# es muss gelten:
print(A.shape[-1] == B.shape[-2], A.shape[1])
print(np.dot(A, B))

True 3
[[ 7  7 17  4]
 [ 9  9 19  0]]


### Cocatenating, Flattening and Adding Dimensions 

In [20]:
#flatten
import numpy as np
A = np.array([[[ 0, 1],
[ 2, 3],
[ 4, 5],
[ 6, 7]],
[[ 8, 9],
[10, 11],
[12, 13],
[14, 15]],
[[16, 17],
[18, 19],
[20, 21],
[22, 23]]])
Flattened_X = A.flatten()
print(Flattened_X)
print(A.flatten(order="C"))
print(A.flatten(order="F"))
print(A.flatten(order="A"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [21]:
#ravel
print(A.ravel())
print(A.ravel(order="A"))
print(A.ravel(order="F"))
print(A.ravel(order="A"))
print(A.ravel(order="K"))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


#### Reshape

![title](reshape.png)

In [25]:
X = np.array(range(24))
Y = X.reshape((3,4,2))
print(X)
Y

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

#### Concatenate

In [27]:
x = np.array([11,22])
y = np.array([18,7,6,9])
z = np.array([1,3,5])
c = np.concatenate((x,y,z))
print(c)

[11 22 18  7  6  9  1  3  5]


#### Adding New Dimension

New dimensions can be added to an array by using slicing and np.newaxis.

In [35]:
x = np.array([2,5,18,14,4])
print(x)
print(np.shape(x))
y = x[:, np.newaxis]
print(y)
np.shape(y)

[ 2  5 18 14  4]
(5,)
[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]


(5, 1)

## Random Numbers & Probability

In [37]:
import random
random_number = random.random()
print(random_number)

0.502986395735698


In [38]:
from random import SystemRandom
crypto = SystemRandom()
print(crypto.random())

0.26153151201872915


Generating a list of random numbers

In [41]:
import random
def random_list(n, secure=True):
    random_floats = []
    if secure:
        crypto = random.SystemRandom()
        random_float = crypto.random
    else:
        random_float = random.random
    for _ in range(n):
        random_floats.append(random_float())
    return random_floats
print(random_list(10, secure=False))

[0.7655377543874983, 0.16022042853077412, 0.39930821152379636, 0.25604854014684575, 0.3925445750379003, 0.862034352355744, 0.9837772553440887, 0.43395948148855634, 0.6281780179363943, 0.6923263384119206]


In [44]:
import numpy as np
RD=np.random.random(10)
print(RD)

[0.9508282  0.7316664  0.62954127 0.83195931 0.18762141 0.43723985
 0.91028638 0.53289942 0.51722794 0.78790742]


In [57]:
# Random Integer Numbers
import random
outcome = random.randint(1,10)
print(outcome)

6


In [54]:
import numpy as np
outcome = np.random.randint( 8, size=10)
print(outcome)

[6 4 4 0 0 0 0 6 1 2]


In [58]:
import random
crypto = random.SystemRandom()
[ crypto.randint(1, 6) for _ in range(10) ]

[4, 1, 3, 6, 4, 6, 4, 3, 6, 4]